### PR TITLE
remove wrong steps

### PR DESCRIPTION
**Pull request by noraj**
the lazy steps can't work since the docker-compose.yml is not standalone:

https://github.com/evait-security/envizon/blob/b786c6c0749a0d725be72808ea0498cd3ed6a827/docker/envizon_prod/docker-compose.yml#L21-L22
https://github.com/evait-security/envizon/blob/b786c6c0749a0d725be72808ea0498cd3ed6a827/docker/envizon_prod/docker-compose.yml#L48

Launching the docker-compose alone without the other files (entrypointscript, dockerfile, upper folders, etc.) will end into this erroneous state:

```
envizon_postgres   | 2020-09-10 20:55:21.084 UTC [52] ERROR:  relation "users" does not exist at character 566                                                                                                                               
envizon_postgres   | 2020-09-10 20:55:21.084 UTC [52] STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
envizon_postgres   |                         pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,                                                                                                                         
envizon_postgres   |                         c.collname, col_description(a.attrelid, a.attnum) AS comment                                                                                                                                    
envizon_postgres   |                    FROM pg_attribute a                                                                                                                                                                                  
envizon_postgres   |                    LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum                                                                                                                              
envizon_postgres   |                    LEFT JOIN pg_type t ON a.atttypid = t.oid                                                                                                                                                            
envizon_postgres   |                    LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation                                                                                                              
envizon_postgres   |                   WHERE a.attrelid = '"users"'::regclass                                                                                                                                                                
envizon_postgres   |                     AND a.attnum > 0 AND NOT a.attisdropped
envizon_postgres   |                   ORDER BY a.attnum
envizon_postgres   | 
envizon_postgres   | 2020-09-10 20:55:21.726 UTC [52] ERROR:  relation "users" does not exist at character 566
envizon_postgres   | 2020-09-10 20:55:21.726 UTC [52] STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
envizon_postgres   |                         pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
envizon_postgres   |                         c.collname, col_description(a.attrelid, a.attnum) AS comment
envizon_postgres   |                    FROM pg_attribute a
envizon_postgres   |                    LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
envizon_postgres   |                    LEFT JOIN pg_type t ON a.atttypid = t.oid
envizon_postgres   |                    LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
envizon_postgres   |                   WHERE a.attrelid = '"users"'::regclass
envizon_postgres   |                     AND a.attnum > 0 AND NOT a.attisdropped
envizon_postgres   |                   ORDER BY a.attnum
envizon_postgres   | 
envizon_postgres   | 2020-09-10 20:55:24.178 UTC [52] ERROR:  relation "users" does not exist at character 566
envizon_postgres   | 2020-09-10 20:55:24.178 UTC [52] STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
envizon_postgres   |                         pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
envizon_postgres   |                         c.collname, col_description(a.attrelid, a.attnum) AS comment
envizon_postgres   |                    FROM pg_attribute a
envizon_postgres   |                    LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
envizon_postgres   |                    LEFT JOIN pg_type t ON a.atttypid = t.oid
envizon_postgres   |                    LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
envizon_postgres   |                   WHERE a.attrelid = '"users"'::regclass
envizon_postgres   |                     AND a.attnum > 0 AND NOT a.attisdropped
envizon_postgres   |                   ORDER BY a.attnum
envizon_postgres   | 
```

### CODE REVIEW

**Comment by blacklist-arcc** [comment]
Thanks for reaching us, we will review this issue soon.

**Comment by evs-ch** [comment]
I'm not entirely sure what exactly is going wrong on your end, but the `docker-compose.yml` actually is "standalone" – the way it's written the "dependencies" (Dockerfile, entrypoint script etc.) are _only_ used in the build context, ie. when you run `docker-compose build`. Otherwise, `image:` is used – either by pulling, or using an existing image of that name/tag.

```yml
    image: evait/envizon
    build:
      context: ../../
      dockerfile: docker/envizon_prod/Dockerfile
```

The error output you get might come from some older images/containers lying around and being used by docker, or maybe by some cookie/state being remembered by your browser, which leads it to submitting this to the app, which – freshly set up – doesn't actually have a user yet and fails, instead of going to the "sign up" step as it should.

I'd advise you check those possibilities, and if you still have this issue afterwards, feel free to open a separate issue so we can get this sorted :)

**Comment by blacklist-arcc** [comment]
maybe run some ´docker rmi ...´ commands in order to delete old images. maybe we should note some "update" notes in the readme.

**Comment by noraj** [comment]
I cleaned cache and it's good now.

**Pull request closed without merging**
